spiffe/spiffe.io

content/spiffe/_index.md, content/spire/_index.md, content/spire/architecture.md, content/spire/getting-started.md, layouts/partials/tabs.html
This PR adds support for "short" titles, i.e. titles that appear differently in the navigation than they do at the top of the document.
=> Add shortened titles for the nav tabs

netlify.toml
This is to address a thorny issue that Netlify is having updating their build infrastructure (long story). We can go back to using `make` commands once that issue is fixed.
=> Use direct Hugo commands in Netlify config

Makefile, config.toml, netlify.toml
There's a lingering issue, pointed out in #36, where Hugo isn't re-fetching JSON from the GitHub Releases API. The `--gc` may help with this issue but I'm not sure, as I'll need to do some more investigation of Netlify's build infrastructure.
=> Use cache clearing for production build

config.toml, layouts/partials/css.html, layouts/partials/javascript.html
This makes the web resource integrity checking optional (and disables it). To re-enable, set `assetintegritychecking` to `true`.
=> Make integrity checking optional

content/spire/getting-started-linux.md
The link to section `#step-8-retrieve-workload-svids` includes the ':' after "Step 8" but that colon is stripped out during markdown processing. This PR fixes that link.
=> Fixes section link in `getting-started-linux.md`

content/spire/overview.md
https://github.com/spiffe/plugin-template/blob/master/SPIRE_PLUGIN_GUIDE.md is not well maintained.
spire repo provides a handy reference for custom plugin implementation.  This is not a comprehensive document guide but it seems to be the most appropriate reference for now.
Although I think we need updated plugin development guide as https://github.com/spiffe/spiffe.io/issues/67 described,  I think spiffe.io should keep being compatible with the latest release.
=> update custom server and agent plugins reference to examples in spire repo

content/downloads/_index.md, content/spire/getting-started-linux.md
- Updates paths to SPIRE binaries built via the SPIRE Makefile
- Removes UpstreamCA and agent bootstrap related text
- Updates texts to require configuration of the data directory for SPIRE Server and SPIRE Agent
=> Updates related to SPIRE #1243

Makefile, layouts/shortcodes/releases.html, layouts/shortcodes/spire-latest.html
This PR adds separate development modes for pinging the GitHub API for release info vs. not. The default `make serve` command now displays an informational blockquote rather than the releases table. The `make serve-with-releases` command will display the table.
Fixes #93
=> Fix GitHub API rate limiting issue

content/spire/try/getting-started-k8s.md
Parent ID is not required when creating an entry via the CLI with the
`-node` flag.
Signed-off-by: Evan Gilman <evan@scytale.io>
=> Remove Parent ID from node entry in k8s guide

content/spire/try/getting-started-k8s.md
Made some fixes to the guide as a result of walking through it using minikube 1.6.2, which uses Kubernetes 1.17.0.
Relevant issue about the fix made to minikube flags:
https://github.com/kubernetes/minikube/issues/6061
=> Some fixes to the Getting started k8s guide

content/spire/docs/configuring.md
Changes:
- On section _Configuring node Attestation - Azure Virtual Machine_ refers to AWS instead of Azure MSI plugin: _For more information on configuring Azure MSI Node Attestors or Resolver plugins, refer to the corresponding SPIRE documentation for the **AWS** SPIRE Server Node Attestor and SPIRE Server Node Resolver on the SPIRE Server, and the SPIRE Agent Node Attestor on the agent._
- On section _Configuring how generated keys are stored on the Agent and Server_: missing underscore at the end of the first line: _This configuration applies to the SPIRE Server and SPIRE Agent
- On section: _Configuring how generated keys are stored on the Agent and Server_, on point **Store on disk** the last sentence is incorrectly referring to “memory“ instead of “disk”: This strategy can be …
=> Added some name fixes at configuring.md

Makefile
This is another try to fix #36 
cc @lucperkins
=> Ignore build cache when building on production mode

Makefile, config.toml, content/spiffe/casestudies/_index.md, layouts/_default/_markup/render-link.html, netlify.toml
- Updates Hugo to the latest version, v0.68.3
- It pins up to that specific version to avoid future Hugo releases breaking the build or content
- Some other minor changes required to make the content render the same way it was with version 0.59.1
=> Updates Hugo and it pins up to an specific version

content/spire/docs/configuring.md
Reported on 6-Apr-2020 by Vlad Botez in SPIFFE/#help Slack channel.
=> Link to SPIRE Agent reference went to SPIRE Server reference

content/spire/try/getting-started-k8s.md
https://github.com/spiffe/spire-tutorials/pull/13 has changed where k8s getting started guide files live, this PR changes the guide to reflect that change.
=> Update k8s getting started guide path to files

layouts/partials/home/newsbar.html
Per Umair Khan in marketing, I’ve temporarily replaced Evan's SPIFFE
intro video with promo text for the SPIFFE Community Day Spring 2020.
We’ll put the video back after April 24, 2020.
=> Temporarily add SPIFFE Community Day Spr 2020 promo

content/spire/concepts.md, content/spire/try/getting-started-k8s.md, content/spire/try/getting-started-linux.md
Links to other pages on spiffe.io that used the full URL would open in
a new browser tab instead of the same browser tab. This commit also
fixes some broken links in the Linux/Mac getting started guide.
=> Shorten intra-site URLs to prevent new browser tabs

README.md, content/spire/docs/install-agents.md, content/spire/docs/install-server.md, layouts/shortcodes/spire-latest.html
Starting from version 0.9.2, SPIRE has been prefixing the git tag name with a `v` (for example `v.0.9.2`), and this caused some mismatches with the installation instructions for the server and agent.
This PR introduces a new parameter to the `latest-spire` shortcode, that can be either `version`,`tag` or `tarball` to be used as necessary.
=> Fix spire server/agent install instructions

content/spire/docs/configuring.md, content/spire/docs/install-server.md
Fix these issues reported by @MarcosDY in his review of the SPIRE docs
to coincide with the release of SPIRE 0.10.0:
* Kubernetes YAML files are in a quickstart subdirectory now
* Recommended location of data_dir is no longer "/opt/spire/.data" but
"/opt/spire/data"
I added a new section to configuring.md describing the data_dir
setting and removed info about data_dir from install-server.md.
=> Fix issues reported by @MarcosDY re SPIRE 0.10.0

layouts/partials/home/newsbar.html
This reverts the spiffe.io home page to the previous state before the Spring 2020 community day info was added.
=> Replace community day info with SPIRE intro video

content/spire/try/getting-started-linux-macos-x.md
* Bump minimum required go version for MacOS.
* Fix some omissions in the MacOS steps.
* Other minor editing.
=> Fixes related to SPIRE 0.10.0 release

content/spire/docs/configuring.md
* JWT SVIDs are now supported for upstream authority
* Remove wrong info about connection_string being a relative path and
refer to recently updated info about data storage paths
=> Clarify upstream authority and data storage info

content/downloads/_index.md, layouts/shortcodes/releases.html
* Explain new v0.10.0 spire-extras tarball & add links
* Clarified requirements for building SPIRE
* Changed "make all" to "make build" for less cruft
* Described build output in a more generic way
=> Update get spire for v0.10.0

CODEOWNERS
Adding Maximiliano (Max) Churichi and Dave Langhorst as spiffe.io
website codeowners so more people can approve PRs. In the CODEOWNERS
file, users are arranged alphabetically by last name.
=> Add additional codeowners for better PR review coverage

content/spire/try/spiffe-library-usage-examples.md
This PR requires that https://github.com/spiffe/go-spiffe/pull/141 is merged first.
=> Added link to SPIFFE auth using JWT with go-spiffe.

config.toml
The URL for the SPIFFE blog has changed. The content of the blog has
been refreshed. This change is per Umair Khan of HPE.
=> Change URL for Medium in header and footer buttons

assets/sass/style.sass, config.toml, layouts/partials/footer.html, layouts/partials/navbar.html
Hi Max, 
Maybe you can take a look at this and get the color styling working?
-Steve
Per Umair Khan, add YouTube social button to header and footer of all
pages. The link points to the SPIFFE YouTube channel.
Currently, the CSS styling for setting the color of the button isn't
working. There doesn't seem to be a styling set up for a YouTube
social icon in the following file:
./resources/_gen/assets/sass/sass/style.sass_9f01a0c1d1634a317edafe1745cc4bff.content
=> Add YouTube social button to header + footer

content/spire/docs/extending.md
Today, Andrew Harding (@azdagron) mentioned the following:
DataStore is no longer pluggable. At some point we may reintroduce it
with a much more simple design, but that time is not yet (and not for
a while, realistically).
=> Remove "Datastore plugins" info per Andrew Harding

content/spire/docs/envoy.md, content/spire/docs/install-agents.md, content/spire/try/getting-started-k8s.md, content/spire/try/oidc-federation-aws.md
- Replaces the reference of `verify_subject_alt_name` (deprecated in new versions of Envoy) by `match_subject_alt_names` on the Envoy guide.
- Updates references to the SPIRE Server pod on some examples to the correct pod name `spire-server-0`
- Updates examples of `kubectl exec` command to include the double dash `(--)` that separates the arguments from the kubectl arguments.
=> Update StringMatcher method to authorized SPIFFE Ids on Envoy page.

content/spire/try/spiffe-library-usage-examples.md
java-spiffe v2 has graduated to be the main version of java-spiffe.
=> Update link to java-spiffe library

config.toml
Fixes an issue that make Hugo generates TOCs starting at `H2` (or `##` in markdown). We want to generate TOCs starting at H1s.
Preview deploy: https://deploy-preview-166--spiffe.netlify.app/downloads/
=> Fixes Table of Content on Downloads page

content/docs/latest/spire/understand/concepts.md
* Fix typo reported by @maxlambrecht
* Adjust image widths for better text readability
* Remove broken intra-doc link
* Other formatting changes for editorial consistency
=> Fix typo and cosmetic tweaks

content/docs/latest/spire/installing/getting-started-k8s.md
Use a single command to start a shell on the workload container rather
than using two separate steps. This was suggested by @maxlambrecht.
I've made a couple additional minor editorial changes also.
=> Combine 2 existing steps in workload container setup

assets/sass/style.sass
Fixes extra spacing accidentally added in the docs sub-site's headings
Preview here: https://deploy-preview-178--spiffe.netlify.app/docs/latest/spiffe/overview/
See difference in the title "SPIFFE Overview" here: https://spiffe.io/docs/latest/spiffe/overview/
=> Fixes docs subsite heading spacing

pull_external.py
Since the introduction of the pull script in a [previous PR](https://github.com/spiffe/spiffe.io/pull/145), a content developer is able to "link" a Markdown file from a different repository to have it pulled in into the website. This allows content de-duplication and reutilization.
By default all the relative links in a pulled in file are rewritten to continue pointing to the original github URL. E.g. if we pull in https://github.com/spiffe/spire/blob/master/doc/spire_agent.md, there's a link in that document that points to `./telemetry_config.md`, then that link is replaced with `https://github.com/spiffe/spire/blob/master/doc/telemetry_config.md` so it keeps working.
This PR considers the case when we also pull in `telemetry_config.md`into the website, so if that happens the URL is …
=> Fixes links between pulled in github files

content/book/index.html, layouts/partials/home/book.html, layouts/partials/navbar.html
Changes some wording on the Book landing page and home page.
Removes the book hosted in this repo and points to its new location.
Removes the "Get the Book" button on the top nav bar.
Preview: https://deploy-preview-186--spiffe.netlify.app/
Book landing page: https://deploy-preview-186--spiffe.netlify.app/book/
=> SPIFFE book changes

content/docs/latest/spire/understand/concepts.md
The text in some of the graphics is too small to read at 80% width, so I increased the width to 100%.
=> Widen SPIRE concepts.md graphics for text legibility

content/docs/latest/spire-integrations/envoy/envoy.md
Fix for #189 - Remove mention of deprecated "enable_sds" SPIRE Agent configuration option
=> Fix for #189 - Remove mention of deprecated "enable_sds"

layouts/shortcodes/figure.html, pull_external.py
Currently, only [inline style](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images) was supported for images in pulled in Markdown content.
This PR adds support for images in reference-style. It also adds support for `alt` and `title` properties.
=> Adds support for images in reference-style

content/downloads/_index.md, layouts/shortcodes/releases.html, layouts/shortcodes/spire-latest.html
Fixes #210 
Previews:
- https://deploy-preview-211--spiffe.netlify.app/docs/latest/deploying/install-server/
- https://deploy-preview-211--spiffe.netlify.app/docs/latest/deploying/install-agents/
- https://deploy-preview-211--spiffe.netlify.app/downloads/
=> Fixes spire-latest shortcode to use GitHub's Latest Release API

content/docs/latest/microservices/envoy.md
The default agent socket path has changed in [#2075](https://github.com/spiffe/spire/pull/2075).
Signed-off-by: Max Lambrecht <maxlambrecht@gmail.com>
=> Update Envoy config example using new default agent socket path

content/docs/latest/deploying/libraries.md
- Removes java-spiffe example that is no longer available and it has been deprecated. (cc @maxlambrecht )
- Updates go-spiffe default branch
=> Updates SPIFFE libraries page

content/docs/latest/deploying/configuring.md, content/docs/latest/deploying/libraries.md
* In configuring.md, replaced link to k8s Token Review API with
different location that doesn't include a version number
* In libraries.md, replaced link to archived c-spiffe library with new
c-spiffe library under development by HPE
=> Fix broken URLs discovered by new link checker

content/docs/latest/deploying/svids.md, content/docs/latest/spiffe-about/get-involved.md, content/docs/latest/spiffe-about/spiffe-concepts.md, layouts/shortcodes/specs.html
Currently they all redirect to the main branch, but we can just go there directly
=> Update links to spiffe's GitHub master branch to main instead

content/docs/latest/deploying/configuring.md
Remove hint for alternate custom storage provider plugins, because that's no longer supported.
See: https://github.com/spiffe/spire/blob/main/doc/spire_server.md#plugin-types -> DataStore
=> Remove outdated paragraph from configuring.md

assets/sass/style.sass, layouts/index.html, layouts/partials/home/cncf.html, layouts/partials/home/news.html
This PR (a) updates the text on the homepage to describe the projects as "graduate projects" of the CNCF, and (b) adds a re-usable news bar to the homepage to announce the change.
=> Announce project as graduated

content/docs/latest/try/getting-started-k8s.md
SPIRE images used on tutorial no longer uses ubuntu based images, in favor of scratch images, that does not contains `/bin/bash` binaries, 
Stop using bash, but call agent api fetch directly
=> Stop executing bash on getting started k8s tutorial

content/docs/latest/try/getting-started-k8s.md
Adds info tooltip to warn of a deprecated config flag (while spinning local cluster using Minikube) for latest Kubernetes versions
N/A
=> Fix minikube deprecated flag

content/docs/latest/keyless/oidc-federation-aws.md
This PR removes `HeadBucket` as it is not currently valid JSON for the IAM policy. Source page:
https://spiffe.io/docs/latest/keyless/oidc-federation-aws/
Fixes a prior PR (#253 ) with the latest state of the GitHub repository.
=> Removed HeadBucket

external.yaml
The build is currently trying to pull the telemetry config file from the spire repo but the file has been moved, which causes the build to break. This PR updates to pull the file from its new location.
From Netlify's logs:
```
4:43:16 PM: Traceback (most recent call last):
4:43:16 PM:   File "./pull_external.py", line 384, in <module>
4:43:16 PM:     main()
4:43:16 PM:   File "./pull_external.py", line 51, in main
4:43:16 PM:     generated_files = _pull_files(yaml_external)
4:43:16 PM:   File "./pull_external.py", line 204, in _pull_files
4:43:16 PM:     generated_files = _process_files(yaml_external)
4:43:16 PM:   File "./pull_external.py", line 187, in _process_files
4:43:16 PM:     abs_path_to_target_file = _copy_file(
4:43:16 PM:   File …
```
=> Fixes broken build

data/users.yaml
Since this original link was added, we've introduced a landing page on our site for Teleport Workload Identity. This is probably a more suitable place to link people who are interested - hence this PR.
No issue.
=> Updates link to Teleport Workload Identity

content/docs/latest/deploying/configuring.md, content/docs/latest/deploying/registering.md, content/docs/latest/try/getting-started-k8s.md
The k8s_sat node attestor has been deprecated for a few releases and will be removed in 1.12.0. This remove the usage of it found in on spiffe.io.
This should only be merged after https://github.com/spiffe/spire-tutorials/pull/140 gets merged.
fixes #325
=> Remove mentions of the k8s_sat node attestor 
