Makefile, README.md, package-lock.json
This PR provides a better overview of running the site locally and how it's published.
=> Improve README instructions

README.md
This updates the `README` to include a broader range of info about working on the site.
=> Add more detailed user instructions

content/spire/_index.md
Signed-off-by: Jenny B. Schaffer <jenny@scytale.io>
=> Correcting wrong Knox project reference.

config.toml
=> Change base URL to add www

content/spire/getting-started-k8s.md
Adding missing `#` to link
Signed-off-by: Marcos G. Yedro <marcosyedro@gmail.com>
=> Fixing link to server log section in k8s guide

content/spire/from-source.md
cc @ajessup
It's a little quick-and-dirty for now but we can iterate on it. Let me know what else you'd like to see for a v1 version of this doc.
=> Add building from source doc for SPIRE

content/spire/from-source.md, layouts/partials/footer.html, layouts/partials/navbar.html
=> Remove building from source doc from navbar

assets/sass/style.sass
Signed-off-by: Jenny B. Schaffer <jenny@scytale.io>
=> Indenting level-5 headers in TOC. Thanks, AJ.

content/spire/overview.md
Signed-off-by: Jenny B. Schaffer <jenny@scytale.io>
=> Getting new SPIFFE/SPIRE Overview into GitHub.

content/spire/overview.md
Signed-off-by: Jenny B. Schaffer <jenny@scytale.io>
=> Fixing incorrectly formatted numbered list.

content/spire/getting-started-k8s.md
The changes are below.
- Fix incorrect descriptions such as "The agent-configmap.yaml file ~" or "socketagent.sock" correctly
- Add a `Register Workloads` section to see a list of SVIDs, not error messages
Please point out if the description in the `Register Workloads` section is not enough...
=> Improve Getting Started Guide for Kubernetes

content/spire/getting-started-k8s.md, content/spire/getting-started-linux.md
Some minor styling fixes
Signed-off-by: Andrew Jessup <ajessup@gmail.com>
=> Applies minor tweaks to getting started guides for readability

content/spire/getting-started-k8s.md
Signed-off-by: Andrew Jessup <ajessup@gmail.com>
=> Fixes wrapping issue

data/users.yaml
=> Edit AJ's list of SPIFFE providers

content/spire/try/getting-started-linux.md
Signed-off-by: David Langhorst <dave@scytale.io>
=> remove some extra characters

assets/sass/style.sass, content/community/_index.md, content/community/presentations/_index.md, content/spiffe/casestudies/_index.md, data/presentations.yaml, layouts/partials/navbar.html, layouts/shortcodes/presentations.html
This change both changes the location of the presentation content as well as how it is presented. It also moves it under community.
This refactor also makes presentation content a little more data driven, so that adding new presentations is easier and multiple pages can be derived from the same content.
=> Refactors presentation content

content/spire/docs/install-agents.md, content/spire/docs/install-server.md
=> Edit new SPIRE Server and Agent installation pages

content/spire/docs/configuring.md
=> Issue 101: Incorrect link to Kubernetes Workload Attestation Plugin

content/spire/comparisons.md
Signed-off-by: zoemccormick <zmm7@cornell.edu>
closes #108
=> Fix Grey Matter spelling and link in documentation

content/spire/try/getting-started-k8s.md
=> Fix some minor editorial issues

content/spire/docs/configuring.md
=> Fix some typos pointed out by @maxlambrecht

assets/sass/style.sass, layouts/partials/home/newsbar.html, layouts/partials/home/what-is.html
Does what it says on the tin!
I thought it looked nice with a full-bleed black background, so I changed the color of the "What is" section below it to a gray, then I made it responsive correctly.
cc: @lucperkins
=> Embed the "Learn the basics" vide on the homepage properly.

content/spire/try/getting-started-k8s.md, content/spire/try/getting-started-linux-macos-x.md
Signed-off-by: Andres Gomez Coronel <andres@scytale.io>
=> Added some minor fixes to both getting started guides.

data/presentations.yaml
=> Add Anthem CNCF Webinar video

data/presentations.yaml
=> Add videos from 24-Apr-2020 SPIFFE Community Day

content/spire/docs/registering.md
Removed inaccurate description of inheritance and added section on mapping workloads to multiple nodes.
=> Amend mapping workloads to multiple nodes

content/spire/docs/upgrading.md
This is a one-off request from @anvega
GitHub Source: spiffe/spire/master/doc/upgrading.md
=> Import upgrading.md from GitHub SPIRE repo

content/spire/try/spiffe-library-usage-examples.md
=> Fix some typos that I overlooked in a recent PR

content/spire/docs/envoy.md
=> Add links to newly published Envoy tutorials

assets/sass/style.sass, layouts/partials/docs/navbar-link.html, layouts/partials/docs/navbar-section.html, layouts/partials/docs/navbar.html, layouts/partials/docs/sidenav-link.html, layouts/partials/navbar.html
Preview: https://5f36ff1a92131200073dfaef--spiffe.netlify.app/
=> Adds back mobile navbar on the docs site

assets/sass/style.sass
Current site: https://5f6b70ecb67b9f0007290fea--spiffe.netlify.app/downloads/
PR Preview: https://deploy-preview-182--spiffe.netlify.app/downloads/
=> Removes extra spacing on the downloads page

content/book/index.html, layouts/_default/baseof.html
This PR adds Google Analytics tracking to SPIFFE Book's hits
=> Adds GA tracking for outbounds hits and book downloads

data/users.yaml
Updated to link to a new page.
=> Istio doesn't use Citadel as a separate concept any more

content/docs/latest/spire/installing/getting-started-k8s.md
Closes spiffe/spire-tutorials#48.
=> Add 'Considerations When Using Kubeadm' section to k8s quickstart

data/presentations.yaml
Signed-off-by: Luciano <lucianozablocki@gmail.com>
=> Add recent presentations from Production Identity Day: SPIFFE + SPIRE at KubeCon + CloudNativeCon NA 2020

content/docs/latest/try/getting-started-k8s.md
I noticed this option is unnecessary.
=> remove unnecessary option

CODEOWNERS
Signed-off-by: Andres Vega <andresv@vmware.com>
=> Add evan2645 and remove anvega from code owners

assets/sass/docs.sass
Fixes #203
Preview site: https://deploy-preview-212--spiffe.netlify.app/docs/latest/spiffe-about/overview/
=> Fixes the double vertical scrollbars on the docs site

content/docs/latest/deploying/configuring.md, content/docs/latest/deploying/registering.md, content/docs/latest/spire-about/spire-concepts.md, data/users.yaml
This PR fixes broken links found on the website surfaced by the implementation of https://github.com/spiffe/spiffe.io/pull/220
=> Fixes broken links

content/docs/latest/deploying/libraries.md
Signed-off-by: Max Lambrecht <maxlambrecht@gmail.com>
=> Add Rust library link to the libraries doc.

content/docs/latest/planning/extending.md
=> Fix #227 - Add link to Plugin SDK in "Extend SPIRE" page

content/docs/latest/planning/extending.md
Replace workload by node under Node Resolver text.
=> Making a small fix on Node Resolver text.

content/docs/latest/spire-about/comparisons.md
=> Replace 0(Zero) with O(Letter O)

layouts/shortcodes/releases.html, pull_external.py
Fixes #250 
Signed-off-by: Maximiliano Churichi <mchurichi@gmail.com>
=> Preloads SPIRE releases list to avoid fetching issues in Hugo build system

data/presentations.yaml
Pretty much what it says on the tin :)
=> Adds sigstore+SPIFFE tutorial and minor fixes

content/book/index.html
This pr fixes #258 
Adds Solving the Bottom Turtle book to the static site content. Fixes links.
Tested via https://6356de8d4fa5e10f981965f9--monumental-klepon-bbaacb.netlify.app/book/
=> Adds Solving the Bottom Turtle book to the static site content.

content/docs/latest/spiffe-about/spiffe-concepts.md
=> Fix wording

content/docs/latest/spiffe-about/overview.md
Updates feature grid to reflect Teleport Machine & Workload Identity's support for JWT-SVIDs.
=> Update feature grid to include JWT SVID for Teleport

content/docs/latest/deploying/libraries.md
Add csharp-spiffe library to the list of libraries
=> Add csharp-spiffe to the list of libraries
